sudo: false

language: generic

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - optipng
    - ghc-7.10.3
    - cabal-install-1.22
    - texlive-full
    - texlive-latex-extra
    - pdftk
    - yui-compressor

before_install:
 - if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then openssl aes-256-cbc -K $encrypted_68ecbf4e4574_key -iv $encrypted_68ecbf4e4574_iv -in .travisdeploykey.enc -out ~/.ssh/id_rsa -d; fi
 - if [ -e ~/.ssh/id_rsa ]; then chmod go-rwx ~/.ssh/id_rsa; fi

 - export PATH=/opt/ghc/7.10.3/bin:/opt/cabal/1.22/bin:$PATH
 - git clone --depth 1 https://github.com/nomeata/latexki ~/latexki
 - cabal update
 - cabal install safe mtl utf8-string old-time parsec
install:
 - cd ~/latexki; ghc --make -O latexki.hs

before_script:
 - mkdir ~/run
 - ln -s $TRAVIS_BUILD_DIR ~/run/data

script:
 - cd ~/run
 - ../latexki/latexki data .
 - rm -rf data
 - mkdir data
 - git -C $TRAVIS_BUILD_DIR archive HEAD | tar -x -C data
 - data/js/minimize.sh
 - echo 'mitschriebwiki.nomeata.de' > CNAME
 - touch .nojekyll

after_success:
 - if [ "$TRAVIS_BRANCH" = "master" -o "$TRAVIS_BRANCH" = "travis" ] && [ "$TRAVIS_SECURE_ENV_VARS" = "true" ] &&  [ "$TRAVIS_PULL_REQUEST" = "false" ]; then $TRAVIS_BUILD_DIR/.deploy.sh; fi


